server:
  port: 8000
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create #create-每次启动都重新创建； none-启动时不自动执行
  datasource:
    platform: h2
    schema: classpath:/db/schme.sql
    data: classpath:/db/data.sql